### PR TITLE
Feat load after event

### PR DESCRIPTION
**Pull request by stephenkerrhs**
Update to how the Facebook and Twitter scripts are being loaded.

### CODE REVIEW

**Comment by zeto** [comment]
:+1:

**Comment by pusewicz** [comment]
:+1:

**Comment by mmorava** [comment]
:+1:

**Comment by zeto** [comment]
Hello !!

**Comment by dobrien501** [comment]
dont want to miss this party!  :+1:

**Comment by zeto** [comment]
@pusewicz where will u be in two weeeks

**Pull request merged**
